version: '3'

services:
  db:
    container_name: spotlight_db
    image: postgres:11.7
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - '5433:5432'

  api:
    container_name: spotlight_api
    build: .
    environment:
      FLASK_ENV: development
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - '5000:5000'

volumes:
  db-data: