apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: spotlight-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spotlight-api
  template:
    metadata:
      labels:
        app: spotlight-api
    spec:
      containers:
      - name: spotlight-api
        image: 553443767398.dkr.ecr.us-east-1.amazonaws.com/spotlight-api:latest
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: spotlight-api-service
spec:
  selector:
    app: spotlight-api
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: LoadBalancer