apiVersion: v1
kind: Service
metadata:
  name: spotlight-api-service
spec:
  selector:
    app: spotlight-api
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: spotlight-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spotlight-api
  template:
    metadata:
      labels:
        app: spotlight-api
    spec:
      containers:
      - name: spotlight-api
        image: 553443767398.dkr.ecr.us-east-1.amazonaws.com/spotlight-api:latest
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: dev-secrets
              key: postgres_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dev-secrets
              key: postgres_password
        - name: POSTGRES_HOST
          value: spotlight-dev.catgi7sgknxw.us-east-1.rds.amazonaws.com
        - name: POSTGRES_PORT
          value: '5432'
        - name: MODEL_HOST
          value: spotlight-model-service
        - name: MODEL_PORT
          value: '5001'
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: dev-secrets
              key: aws-access-key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: dev-secrets
              key: aws-secret-key
        - name: ENV
          value: config.DevelopmentConfig
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: dev-secrets
              key: spotlight-secret
        - name: MODEL_KEY
          valueFrom:
            secretKeyRef:
              name: dev-secrets
              key: model-key
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: spotlight-web-service
spec:
  selector:
    app: spotlight-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: spotlight-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spotlight-web
  template:
    metadata:
      labels:
        app: spotlight-web
    spec:
      containers:
      - name: spotlight-web
        image: 553443767398.dkr.ecr.us-east-1.amazonaws.com/spotlight_web:latest
        env:
        - name: REACT_APP_API_URL
          value: a22d2755ff7db44438ed2bce2639130d-683259215.us-east-1.elb.amazonaws.com
        - name: REACT_APP_VERSION
          value: v1.0
        ports:
        - containerPort: 3000
