class AuditConstants:
    DATASET_CREATED = "DATASET_CREATED"
    DATASET_VERIFIED = "DATASET_VERIFIED"
    DATASET_OWNERS_MODIFIED = "Dataset owners list modified"
    DATASET_SHARED = "DATASET_SHARED"    

class NotificationConstants:
    DATASET_SHARED_TITLE = "A dataset has been shared with you"
    DATASET_SHARED_DETAIL = "You have been granted access to Dataset(s):"


class UserConstants:
    PUBLIC_DOMAINS = ["gmail.com", "yahoo.com", "msn.com", "hotmail.com"]


class Masks:
    HASH_PII_TYPES: set = {"ssn", "ein", "routing", "usa_phone", "cc_number", "ip_address",
                         "zip_code", "currency", "name", "company", "country", "city"}
    HASH_VALUES = {"name":
           [    
              "Barack Obama",
              "Donald Trump",
              "John Adams",
              "Thomas",
              "James Monroe",
              "John Quincy Adams",
              "Andrew Jackson",
              "Martin Van Buren",
              "William",
              "Nitish Kumar",
              "M. K. Gandhi",
              "Martin Luther King",
              "Nelson Mandella",
              "Mother Teresa",
              "Glenn Maxwell",
              "Steve Smith",
              "AB De Villiers",
              "Hency Croni",
              "Brett Lee",
              "Shane Warne",
              "Mitchell Starc",
              "John Tyler",
              "James K. Polk",
              "Zachary Taylor",
              "Millard Fillmore",
              "Franklin Pierce",
              "James Buchanan",
              "Abraham",
              "Andrew Johnson",
              "Ulysses S. Grant",
              "Rutherford B. Hayes",
              "James Garfield",
              "Chester A. Arthur",
              "Grover Cleveland",
              "Benjamin Harrison",
              "Grover Cleveland",
              "William McKinley",
              "Henry Roosevelt",
              "William Howard Taft",
              "Woodrow Wilson",
              "Warren G. Harding",
              "Calvin Coolidge",
              "Herbert Hoover",
              "Tim Cook",
              "Jeff Bezos",
              "Mark Zuckerberg",
              "Steve Jobs",
              "Steve Wozniak",
              "Henry Ford",
              "Jhonty Franklin",
              "Harry",
              "Dwight Eisenhower",
              "John F. Kennedy",
              "Johnson",
              "Richard",
              "Gerald",
              "James Carter",
              "Ronald Reagan",
              "George Bush",
              "Bill Clinton"
          ],
        "country": [
            "Afghanistan",
            "Argentina",
            "Australia",
            "Austria",
            "Bangladesh",
            "Belgium",
            "Brazil",
            "Canada",
            "China",
            "Colombia",
            "Czech Republic",
            "Denmark",
            "Egypt",
            "Ethiopia",
            "France",
            "Georgia",
            "Germany",
            "Hong Kong",
            "Hungary",
            "India",
            "Iraq",
            "Ireland",
            "Israel",
            "Italy",
            "Japan",
            "Malaysia",
            "Maldives",
            "Mauritius",
            "Mexico",
            "Netherlands",
            "New Zealand",
            "Pakistan",
            "Panama",
            "Poland",
            "Portugal",
            "Singapore",
            "South Africa",
            "Spain",
            "Sweden",
            "Switzerland",
            "United Arab Emirates",
            "United Kingdom",
            "United States",
            "Yemen",
            "Zambia",
            "Zimbabwe"
        ],
        "city": [
            "New York",
            "Buffalo",
            "Rochester",
            "Yonkers",
            "Syracuse",
            "Albany",
            "New Rochelle",
            "Mount Vernon",
            "Schenectady",
            "Utica",
            "White Plains",
            "Hempstead",
            "Troy",
            "Niagara Falls",
            "Binghamton",
            "Freeport",
            "Valley Stream",
            "Los Angeles",
            "San Diego",
            "San Jose",
            "San Francisco",
            "Fresno",
            "Sacramento",
            "Long Beach",
            "Oakland",
            "Bakersfield",
            "Anaheim",
            "Santa Ana",
            "Riverside",
            "Stockton",
            "Chula Vista",
            "Irvine",
            "Fremont",
            "San Bernardino",
            "Modesto",
            "Fontana",
            "Oxnard",
            "Moreno Valley",
            "Huntington Beach",
            "Glendale",
            "Santa Clarita",
            "Garden Grove",
            "Oceanside",
            "Rancho Cucamonga",
            "Santa Rosa",
            "Ontario",
            "Lancaster",
            "Elk Grove",
            "Corona",
            "Palmdale",
            "Salinas",
            "Pomona",
            "Hayward",
            "Escondido",
            "Torrance",
            "Sunnyvale",
            "Orange",
            "Fullerton",
            "Pasadena",
            "Thousand Oaks",
            "Visalia",
            "Simi Valley",
            "Concord",
            "Roseville",
            "Chicago",
            "Aurora",
            "Rockford",
            "Joliet",
            "Naperville",
            "Springfield",
            "Peoria",
            "Elgin",
            "Waukegan",
            "Cicero",
            "Champaign",
            "Bloomington",
            "Arlington Heights",
            "Houston",
            "San Antonio",
            "Dallas",
            "Austin",
            "Fort Worth",
            "El Paso",
            "Arlington",
            "Corpus Christi",
            "Plano",
            "Laredo",
            "Lubbock",
            "Garland",
            "Irving",
            "Amarillo",
            "Grand Prairie",
            "Brownsville",
            "Philadelphia",
            "Pittsburgh",
            "Allentown",
            "Erie",
            "Reading",
            "Scranton",
            "Bethlehem",
            "Lancaster",
            "Harrisburg",
            "Altoona",
            "York",
            "State College",
            "Wilkes-Barre"
        ],
        "company": [
		    "Wal-Mart Stores",
		    "Exxon Mobil",
		    "Chevron",
		    "Berkshire Hathaway",
		    "Apple",
		    "Phillips 66",
		    "General Motors",
		    "Ford Motor",
		    "General Electric",
		    "Valero Energy",
		    "AT&T",
		    "CVS Caremark",
		    "Fannie Mae",
		    "UnitedHealth Group",
		    "McKesson",
		    "Verizon Communications",
		    "Hewlett-Packard",
		    "J.P. Morgan Chase & Co.",
		    "Costco Wholesale",
		    "Express Scripts Holding",
		    "Bank of America",
		    "Cardinal Health",
		    "International Business Machines",
		    "Kroger",
		    "Marathon Petroleum",
		    "Citigroup",
		    "Archer Daniels Midland",
		    "AmerisourceBergen",
		    "Wells Fargo",
		    "Boeing",
		    "Procter & Gamble",
		    "Freddie Mac",
		    "Home Depot",
		    "Microsoft",
		    "Amazon.com",
		    "Target",
		    "Walgreen Co.",
		    "WellPoint",
		    "Johnson & Johnson",
		    "American International Group",
		    "State Farm Insurance Cos.",
		    "MetLife",
		    "PepsiCo",
		    "Comcast",
		    "United Technologies",
		    "Google",
		    "ConocoPhillips",
		    "Dow Chemical",
		    "Caterpillar",
		    "United Parcel Service",
		    "Pfizer",
		    "Lowe’s Companies",
		    "Intel Corporation",
		    "Energy Transfer Equity, L.P.",
		    "Cisco Systems, Inc.",
		    "Enterprise Products Partners L.P.",
		    "Aetna Inc.",
		    "The Coca-Cola Company",
		    "Lockheed Martin Corporation",
		    "Best Buy Co., Inc.",
		    "The Walt Disney Company",
		    "CHS Inc.",
		    "Sysco Corporation",
		    "FedEx Corporation",
		    "Merck & Co., Inc.",
		    "INTL FCStone Inc.",
		    "Safeway Inc.",
		    "Johnson Controls, Inc.",
		    "Ingram Micro Inc.",
		    "Plains GP Holdings, L.P.",
		    "World Fuel Services Corporation",
		    "Prudential Financial, Inc.",
		    "Humana Inc.",
		    "The Goldman Sachs Group, Inc.",
		    "Tesoro Corporation",
		    "Liberty Mutual Holding Company Inc.",
		    "Honeywell International Inc.",
		    "United Continental Holdings, Inc.",
		    "HCA Holdings, Inc.",
		    "Deere & Company",
		    "Delta Air Lines, Inc.",
		    "Oracle Corporation",
		    "Morgan Stanley",
		    "Hess Corporation",
		    "Twenty-First Century Fox, Inc.",
		    "E.I. du Pont de Nemours and Company",
		    "Sears Holdings Corporation",
		    "New York Life Insurance Company",
		    "Mondelez International, Inc.",
		    "American Express Company",
		    "Nationwide Mutual Insurance Co.",
		    "The Allstate Corporation",
		    "Tyson Foods, Inc.",
		    "Supervalu Inc.",
		    "TIAA-CREF",
		    "Massachusetts Mutual Life Insurance Company",
		    "CIGNA Corporation",
		    "DIRECTV",
		    "General Dynamics Corporation",
		    "Philip Morris International Inc.",
		    "3M Company",
		    "Time Warner Inc.",
		    "Halliburton Company",
		    "Publix Super Markets, Inc.",
		    "International Paper Company",
		    "McDonald’s Corporation",
		    "Macy’s, Inc.",
		    "The TJX Companies, Inc.",
		    "Fluor Corporation",
		    "Northwestern Mutual Life Insurance Company,Inc.",
		    "Tech Data Corporation",
		    "American Airlines Group Inc.",
		    "The Hartford Financial Services Group, Inc.",
		    "The Travelers Companies, Inc.",
		    "Nike, Inc.",
		    "Occidental Petroleum Corporation",
		    "Avnet, Inc.",
		    "Rite Aid Corporation",
		    "Exelon Corporation",
		    "Qualcomm Incorporated",
		    "Emerson Electric Co.",
		    "Northrop Grumman Corporation",
		    "Duke Energy Corporation",
		    "Capital One Financial Corporation",
		    "Aflac Incorporated",
		    "Raytheon Company",
		    "Staples, Inc.",
		    "EMC Corporation",
		    "Eli Lilly and Company",
		    "Alcoa Inc.",
		    "National Oilwell Varco, Inc.",
		    "Baker Hughes Incorporated",
		    "US Foods, Inc.",
		    "Time Warner Cable Inc.",
		    "Union Pacific Corporation",
		    "Abbott Laboratories",
		    "Xerox Corporation",
		    "Arrow Electronics, Inc",
		    "Kimberly-Clark Corporation",
		    "U.S. Bancorp"
        ]
    }
